### ISSUE TITLE
ImportError: No module named detecttools.ctypes_interface

### ISSUE THREAD

**Issue by alduxvm** [bluemellophone/pydarknet#1]
Hi!

I was trying this module on macos, and after installation, I was going to test the `run_tests.py` changing the location of the cfg and the weights files, but I got this error:

```
Traceback (most recent call last):
  File "run_tests.py", line 99, in <module>
    retcode = run_tests()
  File "run_tests.py", line 34, in run_tests
    from pydarknet import Darknet_YOLO_Detector
  File "/usr/local/lib/python2.7/site-packages/pydarknet-1.0.0.dev1-py2.7.egg/pydarknet/__init__.py", line 10, in <module>
    from ._pydarknet import *
  File "/usr/local/lib/python2.7/site-packages/pydarknet-1.0.0.dev1-py2.7.egg/pydarknet/_pydarknet.py", line 12, in <module>
    from pydarknet.pydarknet_helpers import (_load_c_shared_library, _cast_list_to_c, ensure_bytes_strings)
  File "/usr/local/lib/python2.7/site-packages/pydarknet-1.0.0.dev1-py2.7.egg/pydarknet/pydarknet_helpers.py", line 9, in <module>
    import detecttools.ctypes_interface as ctypes_interface
ImportError: No module named detecttools.ctypes_interface
```

After using google, I cannot locate the `detecttools` module... any help? 

Thanks!

**Comment by alduxvm** [comment]
Scratch that, I found such module in your repositories. Thanks for your contributions!
